name: mobile_app
description: "A new Flutter project."
publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ^3.6.2 


dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  intl: ^0.17.0

  # Added HTTP package for API requests
  http: ^1.1.0

  # Added secure storage for token management
  flutter_secure_storage: ^8.0.0

  # State management
  provider: ^6.0.5

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # For local notifications including foreground
  flutter_local_notifications: ^14.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter: 

  uses-material-design: true  